
export const INPUT_TEXT = "INPUT_TEXT";

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const GET_ZOMATO_SUCCESS = 'GET_ZOMATO_SUCCESS';
export const GET_ZOMATO_DETAIL = 'GET_ZOMATO_DETAIL';